spring:
  application:
    name: todo

  # 1. データベース接続設定
  datasource:
    url: jdbc:postgresql://localhost:5434/todo_db
    username: postgres
    password: postgres  # PostgreSQLインストール時に設定したパスワード
    driver-class-name: org.postgresql.Driver

# 2. MyBatisの設定
mybatis:
  mapper-locations: classpath:mapper/*.xml  # SQLを書くXMLファイルの場所
  type-aliases-package: com.sample.todo.entity # Entityクラスのパッケージ
  configuration:
    map-underscore-to-camel-case: true # DBの snake_case を Javaの camelCase に自動変換

# 3. ログ設定
logging:
  level:
    com.sample.todo.repository: DEBUG